use groupK;
DROP TABLE IF EXISTS atp;
CREATE TABLE atp (
  `ATP` int(11) DEFAULT NULL,
 `Location` varchar(50) DEFAULT NULL,
  `Tournament` varchar(50) DEFAULT NULL,
  `Date` date DEFAULT NULL,
  `Series` varchar(45) DEFAULT NULL,
  `Court` varchar(45) DEFAULT NULL,
  `Surface` varchar(45) DEFAULT NULL,
  `Round` varchar(45) DEFAULT NULL,
  `Best of` int(11) DEFAULT NULL,
  `Winner` varchar(50) DEFAULT NULL,
  `Loser` varchar(45) DEFAULT NULL,
  `WRank` int(11) DEFAULT NULL,
  `LRank` int(11) DEFAULT NULL,
  `WPts` int(11) DEFAULT NULL,
  `LPts` int(11) DEFAULT NULL,
  `W1` int(11) DEFAULT NULL,
  `L1` int(11) DEFAULT NULL,
  `W2` int(11) DEFAULT NULL,
  `L2` int(11) DEFAULT NULL,
  `W3` int(11) DEFAULT NULL,
  `L3` int(11) DEFAULT NULL,
  `W4` int(11) DEFAULT NULL,
  `L4` int(11) DEFAULT NULL,
  `W5` int(11) DEFAULT NULL,
  `L5` int(11) DEFAULT NULL,
  `Wsets` int(11) DEFAULT NULL,
  `Lsets` int(11) DEFAULT NULL,
  `Comment` varchar(45) DEFAULT NULL,
  `B365W` float DEFAULT NULL,
  `B365L` float DEFAULT NULL,
  `EXW` float DEFAULT NULL,
  `EXL` float DEFAULT NULL,
  `LBW` float DEFAULT NULL,
  `LBL` float DEFAULT NULL,
  `PSW` float DEFAULT NULL,
  `PSL` float DEFAULT NULL,
  `MaxW` float DEFAULT NULL,
  `MaxL` float DEFAULT NULL,
  `AvgW` float DEFAULT NULL,
  `AvgL` float DEFAULT NULL
  );
